version: "3"

services:
  fluentd:
    image: fluent/fluentd:latest
    ports:
      - "24224:24224"
    environment:
      - 'FLUENTD_CONF=fluentd.conf'
    volumes:
      - ./file:/fluentd/file
      - ./tmp/fluentd:/fluentd/log
      - ./etc:/fluentd/etc